/* 6IXNIGHTS curated data.
   Dates/prices are curated estimates seeded August 2026 — every card links out
   to live sources. To go fully live later, swap this file for a fetch against
   the Ticketmaster Discovery API (see README). */

const TM = (q) => `https://www.ticketmaster.ca/search?q=${encodeURIComponent(q)}`;
const SG = (q) => `https://seatgeek.com/search?search=${encodeURIComponent(q)}`;
const SH = (q) => `https://www.stubhub.com/find/s/?q=${encodeURIComponent(q)}`;
const MAPS = (q) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q + " Toronto")}`;

/* ---------- SPORTS ----------
   team: jays | raptors | leafs | tfc | argos | farm
   price: typical get-in estimate in CAD */
const SPORTS_EVENTS = [
  {
    id: "sp-jays-0902",
    team: "jays",
    date: "2026-09-02",
    title: "Blue Jays vs Rays",
    venue: "Rogers Centre",
    hood: "Downtown",
    price: 14,
    desc: "Midweek September baseball with playoff-race stakes. 500-level gets silly cheap by first pitch.",
    tags: ["⚾ MLB", "500-level deal"],
    links: [
      { label: "Ticketmaster", url: "https://www.ticketmaster.ca/toronto-blue-jays-tickets/artist/806032", primary: true },
      { label: "SeatGeek", url: SG("Toronto Blue Jays") },
      { label: "StubHub", url: SH("Toronto Blue Jays") },
    ],
  },
  {
    id: "sp-jays-0914",
    team: "jays",
    date: "2026-09-14",
    title: "Blue Jays vs Tigers",
    venue: "Rogers Centre",
    hood: "Downtown",
    price: 12,
    desc: "Monday night vs Detroit — historically one of the cheapest tickets of the season. Bring a glove, sit anywhere.",
    tags: ["⚾ MLB", "Cheapest of the month"],
    links: [
      { label: "Ticketmaster", url: "https://www.ticketmaster.ca/toronto-blue-jays-tickets/artist/806032", primary: true },
      { label: "SeatGeek", url: SG("Toronto Blue Jays vs Tigers") },
    ],
  },
  {
    id: "sp-jays-0915",
    team: "jays",
    date: "2026-09-15",
    title: "Blue Jays vs Tigers",
    venue: "Rogers Centre",
    hood: "Downtown",
    price: 13,
    desc: "Tuesday game two of the Detroit series. Roof open if the weather holds; patio beers on Blue Jays Way after.",
    tags: ["⚾ MLB"],
    links: [
      { label: "Ticketmaster", url: "https://www.ticketmaster.ca/toronto-blue-jays-tickets/artist/806032", primary: true },
      { label: "SeatGeek", url: SG("Toronto Blue Jays vs Tigers") },
    ],
  },
  {
    id: "sp-jays-0916",
    team: "jays",
    date: "2026-09-16",
    title: "Blue Jays vs Tigers",
    venue: "Rogers Centre",
    hood: "Downtown",
    price: 13,
    desc: "Wednesday series finale. Get-in under $15, then you're a five-minute walk from King West for the night's second act.",
    tags: ["⚾ MLB", "Pairs with King W"],
    links: [
      { label: "Ticketmaster", url: "https://www.ticketmaster.ca/toronto-blue-jays-tickets/artist/806032", primary: true },
      { label: "SeatGeek", url: SG("Toronto Blue Jays") },
    ],
  },
  {
    id: "sp-tfc-0923",
    team: "tfc",
    date: "2026-09-23",
    title: "Toronto FC — midweek MLS fixture",
    venue: "BMO Field",
    hood: "Exhibition Place",
    price: 19,
    desc: "South-end supporters section: drums, flags, and the best atmosphere-per-dollar in Toronto sports.",
    tags: ["⚽ MLS", "Supporters section"],
    links: [
      { label: "Ticketmaster", url: TM("Toronto FC"), primary: true },
      { label: "SeatGeek", url: SG("Toronto FC") },
    ],
  },
  {
    id: "sp-argos-1002",
    team: "argos",
    date: "2026-10-02",
    title: "Argonauts — October home game",
    venue: "BMO Field",
    hood: "Exhibition Place",
    price: 15,
    desc: "CFL playoff push, lakefront stadium, tickets regularly under $20. Criminally slept on.",
    tags: ["🏈 CFL", "Under $20"],
    links: [
      { label: "Ticketmaster", url: TM("Toronto Argonauts"), primary: true },
      { label: "SeatGeek", url: SG("Toronto Argonauts") },
    ],
  },
  {
    id: "sp-raps-1007",
    team: "raptors",
    date: "2026-10-07",
    title: "Raptors preseason opener",
    venue: "Scotiabank Arena",
    hood: "Downtown",
    price: 20,
    desc: "The cheapest way to sit close at Scotiabank all year — preseason lower-bowl seats go for weekend-upper-bowl money.",
    tags: ["🏀 NBA", "Lower bowl deal"],
    links: [
      { label: "Ticketmaster", url: TM("Toronto Raptors"), primary: true },
      { label: "SeatGeek", url: SG("Toronto Raptors") },
      { label: "StubHub", url: SH("Toronto Raptors") },
    ],
  },
  {
    id: "sp-leafs-1013",
    team: "leafs",
    date: "2026-10-13",
    title: "Maple Leafs — weeknight vs non-rival",
    venue: "Scotiabank Arena",
    hood: "Downtown",
    price: 55,
    desc: "The only affordable Leafs formula: Tuesday, non-Original-Six opponent, standing room or 300-level singles.",
    tags: ["🏒 NHL", "Standing room"],
    links: [
      { label: "Ticketmaster", url: TM("Toronto Maple Leafs"), primary: true },
      { label: "SeatGeek", url: SG("Toronto Maple Leafs") },
      { label: "StubHub", url: SH("Toronto Maple Leafs") },
    ],
  },
  {
    id: "sp-raps-1028",
    team: "raptors",
    date: "2026-10-28",
    title: "Raptors — early-season weeknight game",
    venue: "Scotiabank Arena",
    hood: "Downtown",
    price: 28,
    desc: "October/November Wednesdays vs non-marquee teams are the sweet spot before holiday pricing kicks in.",
    tags: ["🏀 NBA", "Weeknight sweet spot"],
    links: [
      { label: "Ticketmaster", url: TM("Toronto Raptors"), primary: true },
      { label: "SeatGeek", url: SG("Toronto Raptors") },
    ],
  },
  {
    id: "sp-905-1112",
    team: "farm",
    date: "2026-11-12",
    title: "Raptors 905 — home opener window",
    venue: "Paramount Fine Foods Centre",
    hood: "Mississauga",
    price: 15,
    desc: "G-League: future Raptors, courtside-adjacent seats for $15–25, zero lines. Worth the GO trip.",
    tags: ["🏀 G-League", "Courtside cheap"],
    links: [
      { label: "Ticketmaster", url: TM("Raptors 905"), primary: true },
      { label: "SeatGeek", url: SG("Raptors 905") },
    ],
  },
  {
    id: "sp-marlies-1118",
    team: "farm",
    date: "2026-11-18",
    title: "Marlies — weeknight AHL hockey",
    venue: "Coca-Cola Coliseum",
    hood: "Exhibition Place",
    price: 20,
    desc: "Pro hockey at 1/6th the Leafs price, and half the roster will be up with the big club by spring.",
    tags: ["🏒 AHL", "Family cheap"],
    links: [
      { label: "Ticketmaster", url: TM("Toronto Marlies"), primary: true },
      { label: "SeatGeek", url: SG("Toronto Marlies") },
    ],
  },
];

/* ---------- CONCERTS ----------
   genre: hiphop | rnb | reggae | afro ; size: arena | mid | club */
const CONCERT_EVENTS = [
  {
    id: "c-firstclass",
    genres: ["hiphop"],
    size: "mid",
    date: "2026-08-28",
    title: "First Class Fest — Day 1 (Osamason, Lancey Foux)",
    venue: "The Bowl, Sobeys Stadium",
    price: 65,
    desc: "Underground rap festival takeover — day two runs Saturday with Lucki and Nettspend.",
    links: [
      { label: "Tickets", url: TM("First Class Fest"), primary: true },
      { label: "SeatGeek", url: SG("First Class Fest Toronto") },
    ],
  },
  {
    id: "c-dontoliver",
    genres: ["hiphop", "rnb"],
    size: "arena",
    date: "2026-09-02",
    title: "Don Toliver",
    venue: "Scotiabank Arena",
    price: 50,
    desc: "Wednesday arena show — resale for weekday arena rap routinely dips under face after 4pm day-of.",
    links: [
      { label: "Ticketmaster", url: TM("Don Toliver Toronto"), primary: true },
      { label: "SeatGeek", url: SG("Don Toliver Toronto") },
      { label: "StubHub", url: SH("Don Toliver Toronto") },
    ],
  },
  {
    id: "c-tlc",
    genres: ["rnb"],
    size: "arena",
    date: "2026-09-02",
    title: "TLC · Salt-N-Pepa · En Vogue",
    venue: "RBC Amphitheatre",
    price: 39,
    desc: "90s R&B royalty on the lakefront. Lawn tickets + a blanket is the move.",
    links: [
      { label: "Ticketmaster", url: TM("TLC Toronto"), primary: true },
      { label: "SeatGeek", url: SG("TLC Toronto") },
    ],
  },
  {
    id: "c-logic",
    genres: ["hiphop"],
    size: "arena",
    date: "2026-09-27",
    title: "Logic · Juicy J",
    venue: "RBC Amphitheatre",
    price: 35,
    desc: "End-of-season amphitheatre show — last outdoor rap show of the year, lawn goes cheap.",
    links: [
      { label: "Ticketmaster", url: TM("Logic Toronto"), primary: true },
      { label: "SeatGeek", url: SG("Logic Toronto") },
    ],
  },
  {
    id: "c-history-rnb",
    genres: ["rnb"],
    size: "mid",
    date: "2026-09-17",
    title: "R&B night at History (rotating headliner)",
    venue: "History",
    price: 45,
    desc: "Drake's east-end venue runs a steady diet of touring R&B and rap on weeknights — check the calendar, something's always on.",
    links: [
      { label: "History calendar", url: TM("History Toronto"), primary: true },
      { label: "SeatGeek", url: SG("History Toronto") },
    ],
  },
  {
    id: "c-rebel-hiphop",
    genres: ["hiphop"],
    size: "mid",
    date: "2026-09-24",
    title: "Rebel Thursday — touring rap showcase",
    venue: "Rebel",
    price: 30,
    desc: "The waterfront mega-club's concert side. Thursday shows skew cheaper and end in time for last call upstairs.",
    links: [
      { label: "Rebel events", url: TM("Rebel Toronto"), primary: true },
      { label: "SeatGeek", url: SG("Rebel Toronto") },
    ],
  },
  {
    id: "c-reggae-danforth",
    genres: ["reggae"],
    size: "mid",
    date: "2026-10-01",
    title: "Reggae & dancehall night — Danforth Music Hall",
    venue: "Danforth Music Hall",
    price: 40,
    desc: "The Danforth is Toronto's default room for touring reggae and dancehall acts — watch for Popcaan, Kranium, and Protoje-tier bookings.",
    links: [
      { label: "Ticketmaster", url: TM("Danforth Music Hall reggae"), primary: true },
      { label: "SeatGeek", url: SG("Danforth Music Hall") },
    ],
  },
  {
    id: "c-afro-history",
    genres: ["afro"],
    size: "mid",
    date: "2026-10-08",
    title: "Afrobeats live — touring showcase",
    venue: "History",
    price: 45,
    desc: "Toronto is a top-3 afrobeats market in North America — Rema/Asake/Ayra Starr-tier acts route through History and Coca-Cola Coliseum.",
    links: [
      { label: "Ticketmaster", url: TM("afrobeats Toronto"), primary: true },
      { label: "SeatGeek", url: SG("afrobeats Toronto") },
    ],
  },
  {
    id: "c-velvet",
    genres: ["hiphop", "rnb"],
    size: "club",
    date: "2026-09-09",
    title: "Rising rap & R&B — Velvet Underground",
    venue: "Velvet Underground",
    price: 25,
    desc: "Queen West's 600-cap room: catch next year's History headliners for $20–30. Weeknight shows constantly.",
    links: [
      { label: "Ticketmaster", url: TM("Velvet Underground Toronto"), primary: true },
      { label: "SeatGeek", url: SG("Velvet Underground Toronto") },
    ],
  },
  {
    id: "c-drakeunderground",
    genres: ["rnb", "hiphop"],
    size: "club",
    date: "2026-09-22",
    title: "Live R&B sessions — Drake Underground",
    venue: "The Drake Hotel",
    price: 15,
    desc: "The Drake Hotel's basement stage (no relation to the rapper) runs intimate soul/R&B bills — cheapest live music on Queen West.",
    links: [
      { label: "Drake Hotel events", url: "https://www.thedrake.ca/thedrakehotel/", primary: true },
      { label: "Map", url: MAPS("The Drake Hotel Queen St W") },
    ],
  },
];

/* Artists with no confirmed Toronto date — link to alert pages */
const ARTIST_WATCH = [
  { name: "Drake", note: "Hometown shows sell out in minutes — set the alert now", url: TM("Drake") },
  { name: "The Weeknd", note: "Scarborough's own; stadium runs announce months out", url: TM("The Weeknd") },
  { name: "J. Cole", note: "Historically plays Scotiabank / Budweiser Stage", url: TM("J. Cole") },
  { name: "PartyNextDoor", note: "OVO family — History pop-ups happen with no warning", url: TM("PartyNextDoor") },
  { name: "Daniel Caesar", note: "Toronto R&B king; hometown dates are a lock eventually", url: TM("Daniel Caesar") },
  { name: "Burna Boy", note: "Regular Toronto stops on every tour", url: TM("Burna Boy") },
  { name: "Popcaan", note: "Unruly + OVO ties — dancehall's biggest Toronto draw", url: TM("Popcaan") },
];

/* ---------- NIGHTLIFE ----------
   hood: kingwest | ossington | yorkville | queenwest | ent
   vibe: club | barclub | lounge
   nights: which nights it actually goes (Mon..Sun) */
const NIGHTLIFE_VENUES = [
  {
    id: "n-lostfound",
    name: "Lost & Found",
    hood: "kingwest", hoodLabel: "King West",
    vibe: "club",
    music: ["hiphop", "rnb"],
    nights: ["Thu", "Fri", "Sat"],
    cover: "$10–20, list before 11",
    desc: "King West's reliable hip-hop room — Thursday is the weeknight move, Toronto DJs on rotation.",
    address: "577 King St W",
  },
  {
    id: "n-pettycash",
    name: "Petty Cash",
    hood: "kingwest", hoodLabel: "King West",
    vibe: "barclub",
    music: ["hiphop", "rnb"],
    nights: ["Thu", "Fri", "Sat"],
    cover: "Often free before 11",
    desc: "Basement bar-turned-dancefloor off King — throwback hip-hop and R&B, low pretension, high humidity.",
    address: "487 Adelaide St W",
  },
  {
    id: "n-callherjuliet",
    name: "Call Her Juliet",
    hood: "kingwest", hoodLabel: "King West",
    vibe: "lounge",
    music: ["rnb", "hiphop"],
    nights: ["Wed", "Thu", "Fri", "Sat"],
    cover: "Free–$10 weeknights",
    desc: "R&B-first lounge that turns into a party — the Wednesday/Thursday option when you want vibes without a full club night.",
    address: "553 King St W",
  },
  {
    id: "n-baro",
    name: "Baro",
    hood: "kingwest", hoodLabel: "King West",
    vibe: "barclub",
    music: ["hiphop", "afro", "latin"],
    nights: ["Thu", "Fri", "Sat"],
    cover: "Free with dinner res",
    desc: "Restaurant downstairs, party upstairs (Rooftop/Escobar) — hip-hop blended with Latin and afrobeats. Book dinner, stay up top.",
    address: "485 King St W",
  },
  {
    id: "n-wildflower",
    name: "Wildflower",
    hood: "ent", hoodLabel: "Entertainment District",
    vibe: "club",
    music: ["hiphop", "rnb"],
    nights: ["Fri", "Sat"],
    cover: "$20+, dress code",
    desc: "Upscale hip-hop room at Wellington — bottle-service energy, but the music is genuinely good. Weekends only; pregame elsewhere.",
    address: "550 Wellington St W",
  },
  {
    id: "n-44",
    name: "44 Toronto",
    hood: "ent", hoodLabel: "Entertainment District",
    vibe: "club",
    music: ["hiphop", "rnb"],
    nights: ["Thu", "Fri", "Sat"],
    cover: "$15–20, list helps",
    desc: "Mercer St staple — hip-hop and top 40 with a young crowd. Thursdays are student-heavy and cheap.",
    address: "44 Mercer St",
  },
  {
    id: "n-orchid",
    name: "Orchid",
    hood: "ent", hoodLabel: "Entertainment District",
    vibe: "club",
    music: ["hiphop", "afro"],
    nights: ["Thu", "Fri", "Sat", "Sun"],
    cover: "$20 range",
    desc: "Peter St club that leans hip-hop and afrobeats on rotation — check the weekly lineup, Sundays go too.",
    address: "82 Peter St",
  },
  {
    id: "n-porch",
    name: "The Porch",
    hood: "ent", hoodLabel: "Entertainment District",
    vibe: "barclub",
    music: ["hiphop", "top40"],
    nights: ["Wed", "Thu", "Fri", "Sat"],
    cover: "Usually free early",
    desc: "Rooftop over Adelaide — patio season weeknights with hip-hop-leaning DJs and skyline views. Closes when it rains, obviously.",
    address: "250 Adelaide St W",
  },
  {
    id: "n-apt200",
    name: "Apt 200",
    hood: "queenwest", hoodLabel: "Queen West",
    vibe: "barclub",
    music: ["hiphop", "rnb"],
    nights: ["Wed", "Thu", "Fri", "Sat"],
    cover: "Free most nights",
    desc: "Apartment-styled bar with pool table and a hip-hop soundtrack all week — the best free weeknight hang on this list.",
    address: "1034 Queen St W",
  },
  {
    id: "n-cube",
    name: "Cube",
    hood: "queenwest", hoodLabel: "Queen West",
    vibe: "club",
    music: ["hiphop", "afro", "reggae"],
    nights: ["Fri", "Sat"],
    cover: "$15–25",
    desc: "Queen West club with international, afrobeats and dancehall-heavy rooms — one of the more reliably Caribbean-friendly floors downtown.",
    address: "314 Queen St W",
  },
  {
    id: "n-paintedlady",
    name: "The Painted Lady",
    hood: "ossington", hoodLabel: "Ossington",
    vibe: "barclub",
    music: ["hiphop", "funk", "rnb"],
    nights: ["Wed", "Thu", "Fri", "Sat"],
    cover: "Free–$5",
    desc: "Tiny, loud, zero-pretension Ossington bar — DJs spinning hip-hop and funk most nights, dancing by midnight guaranteed.",
    address: "218 Ossington Ave",
  },
  {
    id: "n-bambis",
    name: "Bambi's",
    hood: "ossington", hoodLabel: "Ossington / Dundas W",
    vibe: "barclub",
    music: ["rnb", "house", "hiphop"],
    nights: ["Thu", "Fri", "Sat"],
    cover: "$5–10 late",
    desc: "Beloved Dundas West basement — R&B and house-leaning selectors, sweaty in the best way. Line moves fast on Thursdays.",
    address: "1265 Dundas St W",
  },
  {
    id: "n-rhum",
    name: "Rhum Corner",
    hood: "ossington", hoodLabel: "Ossington / Dundas W",
    vibe: "lounge",
    music: ["reggae", "dancehall"],
    nights: ["Wed", "Thu", "Fri", "Sat"],
    cover: "Free",
    desc: "Haitian rum bar on Dundas West — dancehall, kompa and reggae on the speakers, rum punch in hand. The weeknight reggae fix.",
    address: "926 Dundas St W",
  },
  {
    id: "n-mahjong",
    name: "Mahjong Bar",
    hood: "ossington", hoodLabel: "Ossington / Dundas W",
    vibe: "lounge",
    music: ["rnb", "hiphop", "house"],
    nights: ["Thu", "Fri", "Sat"],
    cover: "Free",
    desc: "Hidden behind a corner-store front — pink-lit lounge with R&B-leaning DJs. Come early Thursday, it's small.",
    address: "1276 Dundas St W",
  },
  {
    id: "n-soluna",
    name: "Soluna",
    hood: "yorkville", hoodLabel: "Yorkville / Avenue Rd",
    vibe: "lounge",
    music: ["hiphop", "latin", "afro"],
    nights: ["Thu", "Fri", "Sat"],
    cover: "Free with res, table mins",
    desc: "Supper club that flips into a party — hip-hop and Latin sets, Yorkville dress code. Do dinner-into-dancing on a Thursday.",
    address: "314 Avenue Rd",
  },
  {
    id: "n-sofia",
    name: "Sofia",
    hood: "yorkville", hoodLabel: "Yorkville",
    vibe: "lounge",
    music: ["rnb", "hiphop"],
    nights: ["Thu", "Fri", "Sat"],
    cover: "Free, reservations key",
    desc: "Yorkville dining room where the lights drop and the R&B volume rises after 10 — the polished end of the weeknight spectrum.",
    address: "99 Yorkville Ave",
  },
];

const MUSIC_LABELS = {
  hiphop: "Hip-Hop",
  rnb: "R&B",
  reggae: "Reggae",
  dancehall: "Dancehall",
  afro: "Afrobeats",
  latin: "Latin",
  house: "House",
  funk: "Funk",
  top40: "Top 40",
};
